//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhatHanhSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOANHSO
    {
        public DOANHSO()
        {
            this.CT_DOANHSO = new HashSet<CT_DOANHSO>();
        }
    
        public int MaDS { get; set; }
        public Nullable<int> MaNXB { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public Nullable<int> ThanhToan { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual ICollection<CT_DOANHSO> CT_DOANHSO { get; set; }
        public virtual NHAXUATBAN NHAXUATBAN { get; set; }
    }
}
